/* Emit tools/wc2026.data.json from the single-source-of-truth JS modules so the
   Python validator (tools/milp.py) checks the SAME data + model defaults the app
   uses — no more hand-mirrored literals. Run: `npm run gen:data`. */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  C, BASES, TEAMS, FIFA_RANK, STAGE, FIXTURES, MILP_OPT, MILP_AUDIT,
  US_CITIES, MX_CITIES, CA_CITIES, ALL_HOSTS,
} from "../src/data/wc2026.js";
import { REF, DEFAULT_H, DEFAULT_W, LEAD } from "../src/model/burden.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const out = {
  _generated: "Generated by `npm run gen:data` from src/data/wc2026.js + src/model/burden.js. Do not hand-edit.",
  C,
  BASES,
  TEAMS: Object.fromEntries(TEAMS.map((t) => [t.t, { f: t.f, cf: t.cf, g: t.g, o: t.o }])),
  FIFA_RANK,
  STAGE,
  FIXTURES,
  MILP_OPT,
  MILP_AUDIT,
  hosts: { US: US_CITIES, MX: MX_CITIES, CA: CA_CITIES, ALL: ALL_HOSTS },
  model: { H: DEFAULT_H, W: DEFAULT_W, REF, LEAD },
};
const dest = join(__dirname, "..", "tools", "wc2026.data.json");
writeFileSync(dest, JSON.stringify(out, null, 2) + "\n");
console.log("wrote", dest);
